### ISSUE TITLE
Invalid Security Token

### ISSUE THREAD

**Issue by mages-pl** [mrcnpdlk/teryt-api#1]
Cześć, od kilku dni mam problem z pobraniem tokenu w celu nawiązania połaczenia z api. Orientujesz się co może być przyczyną ? W samej klasie nic nie zmieniałem w przy korzystaniu z metod podaje klucz z produkcyjny. 

`mrcnpdlk\Teryt\Exception\Connection  : Invalid Security Token
 /vendor/mrcnpdlk/teryt-api/src/mrcnpdlk/Teryt/Helper.php:65`
`  
 {
             if ($e instanceof \SoapFault) {
                 switch ($e->faultcode ?? null) {
                     case 'a:InvalidSecurityToken':
                     return new Connection(sprintf('Invalid Security Token'), 1, $e);
                 case 'WSDL':
                     return new Connection(sprintf('%s', $e->faultstring ?? 'Unknown'), 2, $e);
                 case 'Client':
                     return new Connection(sprintf('%s', $e->faultstring ?? 'Unknown'), 3, $e);`
`  Exception trace:
`
    `
mrcnpdlk\Teryt\Helper::handleException(Object(SoapFault))
/vendor/mrcnpdlk/teryt-api/src/mrcnpdlk/Teryt/Client.php:183
`

**Comment by mrcnpdlk** [comment]
Nie bardzo rozumiem, przed chwilą testowałem na swoim loginie i haśle i wszystko działa jak należy.
Możesz wstawić kawałek kodu odpowiedzialny za ustawienie danych autentykacyjnych.

**Comment by mages-pl** [comment]
Poniżej przesyłam Ci fragment kodu (dodam że na początku wszystko działało elegancko jednak po kilku dniach kiedy odpalałem skrypt pojawil się ten problem: 
```
    $oClient = new Client();
    $oClient->setConfig('TestPubliczny', '1234abcd', true);
    $oNativeApi = NativeApi::create($oClient);
    $oNativeApi->CzyZalogowany();

    dd($oNativeApi->CzyZalogowany()); // zwraca invalid security token, dotyczy to rowniez jak zaserwuje klucze produkcyjne
```

**Comment by mrcnpdlk** [comment]
Dla testów należy ustawić 
```$oClient->setConfig('TestPubliczny', '1234abcd', false);```
FALSE oznacza, że wpada na inny WSDL.

**Comment by mages-pl** [comment]
@mrcnpdlk tu faktycznie w przypadku testowych parametrów znacznik false okazuje się być rozwiązaniem. Napisałem na szybko metodę aby sprawdzić jak zachowa się na danych produkcyjnych i o dziwo również wszystko gra, choć wcześniej catchował błąd: 
![Zrzut ekranu 2019-12-24 o 11 30 24](https://user-images.githubusercontent.com/11885328/71409170-e5991a00-2640-11ea-94a0-2632eb391235.png)
![Zrzut ekranu 2019-12-24 o 11 30 01](https://user-images.githubusercontent.com/11885328/71409171-e631b080-2640-11ea-88fe-712f013c76fd.png)
Zastanawia mnie czy api terytu może mieć czasami problem z serwowaniem usługi czy sam problem pojawił się przez moją nieuwagę.

**Comment by mrcnpdlk** [comment]
Reasumując, testowałem dziś na każdy ze sposobów i nie widzę problemu.
Daj proszę znać czy temat do zamknięcia.

PS: poszła dziś wersja 1.0.0 na produkcje (php 7.2 + zmiany w tworzeniu instancji Api).

**Comment by mages-pl** [comment]
ok, z tego co widzę u siebie na chwilę obecną wszystko działa można więc zamknąć wątek.
