### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Config' not found

### ISSUE THREAD

**Issue by MarcinPHP** [mrcnpdlk/teryt-api#3]
Cześć,

instalacja poszła bez problemu, ale gdy wstawiam prosty kod:

```
require("./vendor/autoload.php");
use mrcnpdlk\Teryt\Client;
use mrcnpdlk\Teryt\NativeApi;

$oConfig = new Config([
    'username'     => 'XXX',
    'password'     => 'XXX',
    'isProduction' => true,
]);
$oNativeApi = NativeApi::create($oConfig);
```

Wyrzuca mi błąd że nie ma klasy Config.
Serwer: PHP 7.3, soapClient jest dostępny.

Dzięki za pomoc

**Comment by MarcinPHP** [comment]
Ok, rozwiązane.

Popraw na stronie głównej, są dwa błędy:
1. dodaj: use mrcnpdlk\Teryt\Config;
2. w przykładzie tworzysz klasę do zmiennej $oNativeApi, a potem używasz $NativeApi.

**Comment by mrcnpdlk** [comment]
Issue resolved PR #4
