### ISSUE TITLE
Compatibility with higher psr/log versions

### ISSUE THREAD

**Issue by dbojdo** [mrcnpdlk/teryt-api#6]
As for now there is no way to install the lib when you use psr/log in version higher than 1.x, as mrcnpdlk/lib-configuration requires only 1.x or 2.x

**Comment by pedrosik** [comment]
Hi, any possibility to merge that ?

**Comment by secit-pl** [comment]
+1 for this

**Comment by mrcnpdlk** [comment]
Ver 1.1.0 resolves problem.
